### ISSUE TITLE
Really Nice project but too laggy! Unity 5.5.1f1

### ISSUE THREAD

**Issue by RealAquilus** [zios/unity-themes#15]
Hi Guys i have installed the theme and it works! But in Unity 5.5.1 is actually unitilizable cause the editor start lag hard. I check the CPU usage but is the same of the normale theme so i don't know.
I hope this help :)

**Comment by Teascade** [comment]
Can confirm, I just downloaded Unity 5.5.1f1 and only set up this plugin for a new project I made specifically for this test, and for me the results are pretty similar, but not quite, here's some extra info;

When I switched the theme to 'Simplicity' my CPU usage went from 8% to up to 50% (presumably because some loops etc. were failing, which also causes these errors to show up), but when I use the default theme CPU usage seems pretty regular, so I'd expect the problem is in Simplicity. Like I said before activating simplicity constantly spews these error messages for me too;

```
NullReferenceException: Object reference not set to an instance of an object
Zios.Utility.RebuildInspectors ()
Zios.Interface.Theme.Update ()
Zios.Interface.ThemeWindow.OnGUI ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:249)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:242)
UnityEditor.HostView.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:76)
```

Hope this helps, I'd really love to see this plugin work properly, since the default theme for Unity is so horrible that I'm having a lot of trouble coming from Unreal Engine to try out Unity, and I really don't have $35/mo to put into this just for the looks 😅

**Comment by bradsmithee** [comment]
The lag you are both experiencing is from an error interrupting script flow and constantly plastering the console.  The previously released version (r522) was only built for 5.5 to 5.5.0f3.  I'll look into fixing the current 5.5.1 issues as well as making the system more future-proof (if possible).

**Comment by RealAquilus** [comment]
Thanks! Can't wait for this fix! i love this project ahahaha

**Comment by Srki94** [comment]
Hey, I'm running this on 5.5.0f3, Build 4 r522.
I experience some form of lag as well.
Most noticeable when I switch to play mode (it takes way longer than it does with the stock theme) or when I switch from the Play window to the Scene window, during Play mode.
I also notice longer "compile time" when I make a change in my IDE and go back to Unity. It feels like whole UI refreshes and takes a bit longer to become responsive. It looks great and all, but having this "lag" every time I make some change really kills it for me. Not sure is this the same lag that people mention in this thread though.

**Comment by bradsmithee** [comment]
The new version (releasing very soon) should work from Unity 5.0 to 5.6, address play mode delays, and offer significantly increased performance all-around.

**Comment by RealAquilus** [comment]
You made my day Man!!! Can't wait for this release :D

**Comment by bradsmithee** [comment]
[Fixed](https://github.com/zios/unity-themes/releases/tag/r549)
